version: "3.7"

services:
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    expose:
      - "5432"
    restart: always
    volumes:
      - db_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "hb123"
      POSTGRES_DB: "campaigndb"
volumes:
  db_volume: